### ISSUE TITLE
ioutil.ReadAll方法有时候会导致一些性能问题

### ISSUE THREAD

**Issue by hantmac** [alibabacloud-go/tea#11]
https://github.com/alibabacloud-go/tea/blob/c132d91088dc6760d9ea46a44b180667e81071d6/tea/tea.go#L170

ReadAll调用了内部方法readAll，如果用ioutil.ReadAll来读取即使只有1byte也会申请512byte，如果数据量大的话浪费的更多每次都会申请512+2*cap(b.buf)，假如我们有1025byte那么它就会申请3584byte，浪费了2倍还多,在网络应用有大量请求过来时就容易导致内存严重浪费，严重时还会内存泄漏。
关于ReadAll的具体源码分析可以看下这篇博文，https://juejin.im/post/5d5be347f265da03b94ff66b

**Comment by JacksonTian** [comment]
学习了。我们看下怎么优化更好。也欢迎为我们提交 PR

**Comment by wenzuochao** [comment]
Thanks for your contribution! The pull request is merged. #15
