### ISSUE TITLE
Could you add a LICENSE file to tea-xml

### ISSUE THREAD

**Issue by vaikas** [alibabacloud-go/tea#70]
Hi there :)

I was unable to create this issue in the repo that this matter pertains to, which is:

https://github.com/alibabacloud-go/tea-xml

Seems to be missing the LICENSE file like is in this repo:
https://github.com/alibabacloud-go/tea-xml

This is causing a bit of grief, would you mind adding a LICENSE file to tea-xml as well? It's preventing us from bringing things in properly here:
https://github.com/sigstore/policy-controller/pull/236

**Comment by cpanato** [comment]
also need for https://github.com/alibabacloud-go/cr-20160607

**Comment by vaikas** [comment]
https://github.com/alibabacloud-go/tea-xml/pull/1

**Comment by yndu13** [comment]
https://github.com/alibabacloud-go/tea-xml/releases/tag/v1.1.3
