### ISSUE TITLE
注释乱写？还不如不写。复制完了，都没有改， 具体如下 

### ISSUE THREAD

**Issue by icetech233** [alibabacloud-go/tea#75]
在 tea.go里面

// Convert is use convert map[string]interface object to struct
func Convert(in interface{}, out interface{}) error {
	byt, _ := json.Marshal(in)
	decoder := jsonParser.NewDecoder(bytes.NewReader(byt))
	decoder.UseNumber()
	err := decoder.Decode(&out)
	return err
}

// Convert is use convert map[string]interface object to struct
func Recover(in interface{}) error {
	if in == nil {
		return nil
	}
	return errors.New(fmt.Sprint(in))
}

**Comment by yndu13** [comment]
感谢批评指正
